### ISSUE TITLE
セレクトボックスにCSSを充てる

### ISSUE THREAD

**Issue by KojiTakahara** [KojiTakahara/servant#5]
``` css
#zozo > select {
    font-size: 14px;
    border: 1px solid #888;
    border-radius: 0px;
    color: black;
    padding: 12px;
    width: 300px;
    -webkit-appearance: none;    
    background-color: white;
    background-transparency: 0.5;
    background-position: right 15px top 22px;
    background-size: 18px 18px;
}
#zozo > select:active {
    border: 1px solid #fff;
}
#zozo {
    margin: 20px;
}
```

``` html
<div id="zozo">
  <select>
    <option>Select an option</option>
  </select>
</div>
```
